name: random_person_generator
description: Aplicacao para obtencao de pessoa aleatoria da API.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: 7.2.0
  # Bloc for state management
  flutter_bloc: 8.1.1
  # Value equality
  equatable: 2.0.5
  # Functional programming thingies
  dartz: 0.10.1
  # Remote API
  internet_connection_checker: 0.0.1+3
  dio: 4.0.6
  # Local cache
  shared_preferences: 2.0.15
  # Animations
  rive: ^0.9.0
  # Map
  map_launcher: ^2.0.0

  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^6.0.7096

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  mockito: 5.2.0
  build_runner: 2.2.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf