name: tarefa_2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: 7.2.0
  # Bloc for state management
  flutter_bloc: 8.1.1
  # Value equality
  equatable: 2.0.5
  # Functional programming thingies
  dartz: 0.10.1
  # Remote API
  connectivity: 3.0.6
  http: 0.13.5
  # Local cache
  shared_preferences: 2.0.15

  cupertino_icons: ^1.0.2
  dio: 4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: 5.2.0
  build_runner: 2.1.0
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true