// Mocks generated by Mockito 5.2.0 from annotations
// in tarefa_2/test/features/person/presentation/bloc/person_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tarefa_2/core/error/failures.dart' as _i6;
import 'package:tarefa_2/core/usecases/usecase.dart' as _i8;
import 'package:tarefa_2/features/person/domain/entities/person.dart' as _i7;
import 'package:tarefa_2/features/person/domain/repositories/person_repository.dart'
    as _i2;
import 'package:tarefa_2/features/person/domain/usecases/get_random_person.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePersonRepository_0 extends _i1.Fake implements _i2.PersonRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetRandomPerson].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRandomPerson extends _i1.Mock implements _i4.GetRandomPerson {
  MockGetRandomPerson() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PersonRepository get randomPersonRepository =>
      (super.noSuchMethod(Invocation.getter(#randomPersonRepository),
          returnValue: _FakePersonRepository_0()) as _i2.PersonRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Person>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i3.Either<_i6.Failure, _i7.Person>>.value(
                  _FakeEither_1<_i6.Failure, _i7.Person>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Person>>);
}
